Install cvc4

diff --git a/cry b/cry
--- a/cry
+++ b/cry
@@ -14,7 +14,7 @@ function setup_dist_bins() {
 }
 
 function download_z3() {
-  [[ -x "$BIN/z3" || -x "$BIN/z3.exe" ]] && return
+  [[ -x "$BIN/z3" || -x "$BIN/z3.exe" || "$(command -v z3)" ]] && return
   version="${1:-"4.8.7"}"
 
   mkdir -p "$BIN"
@@ -36,17 +36,44 @@ function download_z3() {
   fi
 }
 
+function download_cvc4() {
+  [[ -x "$BIN/cvc4" || -x "$BIN/cvc4.exe" || "$(command -v cvc4)" ]] && return
+  version="${1:-"1.7"}"
+
+  mkdir -p "$BIN"
+  os="${RUNNER_OS:-${OSTYPE:-Linux}}"
+  ext=""
+  case "$os" in
+    Linux | linux-gnu) file="x86_64-linux-opt" ;;
+    Windows | msys | cygwin | win32)
+      file="win64-opt.exe"
+      ext=".exe"
+      ;;
+    macOS | darwin*)
+      if ! command -v brew; then
+        echo "Error: Only homebrew installer is supported for automatic macOS downloads"
+        exit 1
+      fi
+      brew tap cvc4/cvc4
+      brew install cvc4/cvc4/cvc4
+      return
+      ;;
+  esac
+  curl -o "$BIN/cvc4$ext" -sL "https://github.com/CVC4/CVC4/releases/download/1.7/cvc4-$version-$file"
+  [[ ! "$os" =~ Windows|msys|cygwin|win32 ]] && chmod +x "$BIN/cvc4"
+}
+
 function show_usage() {
   cat << EOM
 Usage: $0 COMMAND COMANND_OPTIONS
 Available commands:
-  run                     Run Cryptol
-  build                   Build Cryptol
-  haddock                 Generate Haddock documentation
-  install z3|test-runner  Install program to $BIN
-  test                    Run some tests
-  test-dist               Run some tests using the stripped binaries
-  exe-path                Print the location of the local executable
+  run                          Run Cryptol
+  build                        Build Cryptol
+  haddock                      Generate Haddock documentation
+  install z3|cvc4|test-runner  Install program to $BIN if needed
+  test                         Run some tests
+  test-dist                    Run some tests using the stripped binaries
+  exe-path                     Print the location of the local executable
 EOM
 }
 
@@ -85,6 +112,7 @@ case $COMMAND in
   install)
     case "$1" in
       z3 | Z3) download_z3 "4.8.7" ;;
+      cvc4 | CVC4) download_cvc4 "1.7" ;;
       test-runner) setup_external_tools ;;
     esac
     ;;
